name: despliega a Azure

on: [push]

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
    - name: probando
      run: echo ${{ secrets.USERNAME }}
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        source: "site/*"
        target: "/var/www/html"
